name: gem-nft-contract - Contract Bugs
description: Report CodeReview by October 8, 2024. Report contract bugs for gem-nft-contract service.
title: "[Gem-nft-contact - Contract Bugs]: "
labels: ["codeReivew: gem-nft"]
assignees:
  - mehdi-defiesta
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Make sure you are referencing codeReview branch. 
  - type: textarea
    id: Describe the bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: Tell us what you see! 
      value: "Describe the bug and its behavior! You can reference the problematic code using links (codeReview branch)"
    validations:
      required: true
  - type: textarea
    id: Impact
    attributes:
      label: Impact
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    id: Recommendation
    attributes:
      label: Recommendation
      description: If applicable, add screenshots to help explain your Recommendation.
  - type: textarea
    id: Exploit Scenario
    attributes:
      label: Exploit Scenario
  - type: textarea  
    id: Demo
    attributes:
      label: Demo
